development:
  adapter: postgresql
  host: 127.0.0.1
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock
  database: brigaderia_development
  username: root
  password: 
  encoding: utf8
  reconnect: false
  pool: 5

test: &TEST
  adapter: postgresql
  host: 127.0.0.1
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock
  database: brigaderia_test
  username: root
  password: 
  encoding: utf8
  reconnect: false
  pool: 5

cucumber:
  <<: *TEST

production: &PRODUCTION
  adapter: postgresql
  host: 127.0.0.1
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock
  database: brigaderia
  username: root
  password: 
  encoding: utf8
  reconnect: false
  pool: 5

alpha:
  <<: *PRODUCTION

preproduction:
  <<: *PRODUCTION

